#!/bin/sh

echo "Counter Strike Updater..." &> /var/log/cs2-update.log
su - steam -c "/home/steam/cs2server update-lgsm  && /home/steam/cs2server update" &> /var/log/cs2-update.log

# Remove the ssh force logout command
sed -e '/Match User root/d' \
    -e '/.*ForceCommand.*droplet.*/d' \
    -i /etc/ssh/sshd_config

systemctl restart ssh
