#!/bin/sh

log_file=/var/log/cs2-update.log

echo "Counter Strike Updater..." >> $log_file
su - steam -c "/home/steam/cs2server update-lgsm  && /home/steam/cs2server update" >> $log_file

# Remove the ssh force logout command
sed -e '/Match User root/d' \
    -e '/.*ForceCommand.*droplet.*/d' \
    -i /etc/ssh/sshd_config

systemctl restart ssh
